<?php

use Drupal\nord_evasion_event\Entity\Event;
use Drupal\nord_evasion_event\Entity\EventList;
use Drupal\nord_evasion_event\Entity\EventListNodeInterface;
use Drupal\nord_evasion_event\Entity\EventNodeInterface;
use Drupal\nord_evasion_event\Entity\EventType;
use Drupal\nord_evasion_event\Entity\EventTypeTermInterface;
use Drupal\nord_evasion_event\Manager\EventListManager;
use Drupal\nord_evasion_event\Manager\EventManager;

/**
 * Implements hook_help().
 */
function nord_evasion_event_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dillon module.
    case 'help.page.nord_evasion_event':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;
    default:
  }
}

function nord_evasion_event_entity_bundle_info_alter(array &$bundles) {
  $bundles['node'][EventNodeInterface::NODE_BUNDLE]['class'] = Event::class;
  $bundles['node'][EventListNodeInterface::NODE_BUNDLE]['class'] = EventList::class;
  $bundles['taxonomy_term'][EventTypeTermInterface::TERM_VOCABULARY]['class'] = EventType::class;
}

/**
 * Implements hook_preprocess().
 */
function nord_evasion_event_preprocess_node(&$variables) {
  /** @var EventListManager $eventListManager */
  $eventListManager = Drupal::service(EventListManager::class);
  $variables = $eventListManager->addEventListVariablesToPreProcessNodeVariables($variables);

  /* @var EventManager */
  $eventManager = Drupal::service(EventManager::class);
  $variables = $eventManager->addEventVariablesToPreprocessNode($variables);

}
