<?php

use Drupal\nord_evasion_home\Controller\FrontPageController;
use Drupal\nord_evasion_home\Entity\Home;
use Drupal\nord_evasion_home\Entity\HomeNodeInterface;
use Drupal\nord_evasion_home\Manager\HomeManager;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\adimeo_tools\Service\LanguageService;

/**
 * Implements hook_metatag_route_entity().
 *
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return mixed
 */
function nord_evasion_home_metatag_route_entity(RouteMatchInterface $route_match) {
  $routeName = $route_match->getRouteName();
  if ($routeName == FrontPageController::ROUTE_NAME) {
    $homeManager = HomeManager::me();
    $homeId = $homeManager->getFrontPageNodeId();
    if (!empty($homeId)) {
      $languageService = LanguageService::me();
      $homeNode = $languageService->load('node', $homeId);
      if (!empty($homeNode)) {
        return $homeNode;
      }
    }
  }
}

function nord_evasion_home_entity_bundle_info_alter(array &$bundles) {
  $bundles['node'][HomeNodeInterface::NODE_BUNDLE]['class'] = Home::class;
}
